### ISSUE TITLE
eleview reports an error on installation

### ISSUE THREAD

**Issue by Geoloog** [JamesFysh/eleview#1]
Hi James,

I`ve just installed QGIS 2.16.1 on my computer.  When I try to install your Elevation View plugin (version 0.40) the following error pops up:

Error loading plugin

The plugin seems to be invalid or have unfulfilled dependencies.  It has been installed, but can`t be 
loaded.  if you really need this plugin, you can contact it`s author or QGIS users group and try to solve the problem.  If not, you can just uninstall it.  Here is the error message below:

The plugin is broke.  Python said:
No module named qgsprojectionselectionwidget

I don`t know how this works but please contact me direct on hendrik.bosman@gmail.com if needed.

Kindest regards,

Hendrik

![image](https://cloud.githubusercontent.com/assets/22645522/19128573/34a12c64-8b44-11e6-8874-9149eed1251b.png)

**Comment by JamesFysh** [comment]
I believe that version 0.4.1 corrects this issue.  Please respond within the next week if this is not the case, after which I will close the issue.

**Comment by Geoloog** [comment]
You may close the issue as it is solved. Thank you for your effort.

Regards

Hendrik

Op 09 Okt 2016 10:33, het "James Fysh" notifications@github.com geskryf:
